#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 28 11:52:45 2022

@author: Ella
"""
import numpy as np
import torch

x1,x2 = (1,4), (-1,2)
h1,h2 = (-1,2,0,4), (0,1,3,-1)
batch = 4
x=np.linspace(x1,x2,batch)
print(x)

x_array = np.random.rand(5,1) * 10
print(x_array)

a = torch.randn(4, 4)


y= torch.argmax(a, dim=1).unsqueeze(-1)
print(y.size())
z=torch.gather(a,1,y)
print(z)

a = torch.tensor([[1, 2,  3,  4]])
print(a.size())                           

y=torch.zeros(1,1,dtype=int)
b = torch.gather(a,1,y)
print(b)

for i in range(2):
    print(i)